
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW ATTACK CHOICE ENEMY GOTO ID LBRACE NUMBER RBRACE ROOM STRING TEXTscript : roomsrooms : rooms roomrooms : roomroom : ROOM ID LBRACE stmts RBRACEstmts : stmts stmtstmts : stmtstmt : TEXT STRINGstmt : CHOICE STRING ARROW IDstmt : ENEMY STRING ID NUMBERstmt : ATTACKstmt : GOTO ID'
    
_lr_action_items = {'ROOM':([0,2,3,5,15,],[4,4,-3,-2,-4,]),'$end':([1,2,3,5,15,],[0,-1,-3,-2,-4,]),'ID':([4,14,19,21,],[6,20,22,23,]),'LBRACE':([6,],[7,]),'TEXT':([7,8,9,13,16,17,20,23,24,],[10,10,-6,-10,-5,-7,-11,-8,-9,]),'CHOICE':([7,8,9,13,16,17,20,23,24,],[11,11,-6,-10,-5,-7,-11,-8,-9,]),'ENEMY':([7,8,9,13,16,17,20,23,24,],[12,12,-6,-10,-5,-7,-11,-8,-9,]),'ATTACK':([7,8,9,13,16,17,20,23,24,],[13,13,-6,-10,-5,-7,-11,-8,-9,]),'GOTO':([7,8,9,13,16,17,20,23,24,],[14,14,-6,-10,-5,-7,-11,-8,-9,]),'RBRACE':([8,9,13,16,17,20,23,24,],[15,-6,-10,-5,-7,-11,-8,-9,]),'STRING':([10,11,12,],[17,18,19,]),'ARROW':([18,],[21,]),'NUMBER':([22,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,],[1,]),'rooms':([0,],[2,]),'room':([0,2,],[3,5,]),'stmts':([7,],[8,]),'stmt':([7,8,],[9,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> rooms','script',1,'p_script','parser.py',10),
  ('rooms -> rooms room','rooms',2,'p_rooms_multiple','parser.py',17),
  ('rooms -> room','rooms',1,'p_rooms_single','parser.py',23),
  ('room -> ROOM ID LBRACE stmts RBRACE','room',5,'p_room','parser.py',28),
  ('stmts -> stmts stmt','stmts',2,'p_stmts_multiple','parser.py',33),
  ('stmts -> stmt','stmts',1,'p_stmts_single','parser.py',38),
  ('stmt -> TEXT STRING','stmt',2,'p_stmt_text','parser.py',43),
  ('stmt -> CHOICE STRING ARROW ID','stmt',4,'p_stmt_choice','parser.py',48),
  ('stmt -> ENEMY STRING ID NUMBER','stmt',4,'p_stmt_enemy','parser.py',53),
  ('stmt -> ATTACK','stmt',1,'p_stmt_attack','parser.py',58),
  ('stmt -> GOTO ID','stmt',2,'p_stmt_goto','parser.py',63),
]
